### ISSUE TITLE
It looks like it doesn't recognize and apply RTC_CENTER 

### ISSUE THREAD

**Issue by cyrilpreiss** [nytimes/aframe-loader-3dtiles-component#7] opened 2022-01-30 19:59 UTC
As i'm having issues with my metashape tilesets with this library, i have asked help on the metashape forum. 

And here is the answer:

https://www.agisoft.com/forum/index.php?topic=14118.msg62203#msg62203

> It looks like aframe doesn't recognize and apply RTC_CENTER property from the Batched 3D Model Feature Table:
http://docs.opengeospatial.org/cs/18-053r2/18-053r2.html#141

> This property specifies offset that needs to be added to all vertex coordinates, and without this offset vertex coordinates are shifted away from their corresponding bounding volumes.

Could you check this out ?

**Comment by Avnerus** [comment] 2022-02-01 08:26
Hey there @cyrilpreiss,
Thank you for reporting this issue!

First, just a clarification for further issues, the A-Frame component is wrapper around our three.js library: [three-loader-3dtiles](https://github.com/nytimes/three-loader-3dtiles), so if you're having general issues viewing tilesets, that would probably be the best place to report them.

To the matter at hand, you're right. I have so far only encountered the `RTC_CENTER` property in point clouds and it is supported there, but not in mesh tiles (I haven't tested metashape exports as of yet).
However, it seems the people at metashape updated the discussion with the following statement:
```
We updated Cesium 3D tiles export to use root tile transform instead of RTC_CENTER
property in Metashape 1.8.1 build 13915.
```
This means it might work well now with the updated version of Metashape, are you able to test it?
The fact they made this change quickly might mean that the community is converging away from `RTC_CENTER` and into using transform matrices. However, if we encounter more cases requiring this feature, we could definitely add it.

Let me know how it works!
PS. You have another issue still open, could you comment or close that one?
Thanks,

/Avner

**Comment by cyrilpreiss** [comment] 2022-02-02 15:38
Hi,

First, the guy from metashape wrote Aframe in his answer but he should have wtritten aframe-loader-tiles instead.

In the new metashape version they fixed an issue regarding the max error value that had to be set to 1.

The RTC_center not being applied is specific to your library. 

If you need a tileset from metashape for your tests let me know.

**Comment by Avnerus** [comment] 2022-02-02 16:04
Hi @cyrilpreiss,

> The RTC_center not being applied is specific to your library.

Are you sure they didn't fix it? They specifically mention moving from `RTC_CENTER` to using tile transforms ([latest comment on that thread](https://www.agisoft.com/forum/index.php?topic=14118.msg62354#msg62354)). Have you tried that build 13915?

As I wrote, I do recognize that this is not applied in our library, however if they did move away from it, a fix might not be as urgent.

**Comment by cyrilpreiss** [comment] 2022-02-02 17:50
Yes i tried and it still doesn't work

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Avnerus** [comment] 2022-02-02 17:55
Got it, 
If you could please provide me with a tileset created by build 13915 I can check it out.
Have you confirmed that the tileset no longer contains the `RTC_CENTER` property?
Thanks!

**Comment by cyrilpreiss** [comment] 2022-02-02 21:39
My bad, when i answered you today i was in a plane and i hadn't noticed the last input on the metashape forum about version 13915. I'm sorry, i will check with this new version as soon as possible and let you know

**Comment by Avnerus** [comment] 2022-02-03 08:07
No worries! Have safe travels and let me know how it works with the new version.

**Comment by cyrilpreiss** [comment] 2022-02-03 15:24
Hi, it seems to work almost fine now.

https://www.gigascope.net/vr/streetart1ok/

(vr floor isn't set yet)

but there is still a small issue, the first tile layer is not aligned: If you open the link above and walk backward until it shows the less defined layer you will see it shows up in a different place and rotated.

**Comment by Avnerus** [comment] 2022-02-07 13:12
Hi,
Yes I tested this now and I believe the cause is a certain race condition in which the transform matrix of the tileset is being updated before the A-Frame object3D properties are fully applied.
I tested out a fix. Could you please try it using the following url?
```
https://cdn.jsdelivr.net/gh/nytimes/aframe-loader-3dtiles-component@0b2d2bcecf020c8b2b3d31d24e35aab4e1eda31a/dist/aframe-loader-3dtiles-component.min.js
```

**Comment by Avnerus** [comment] 2022-02-28 15:28
@cyrilpreiss I now merged this fix, hope it solved your issue!
I am closing this but feel free to re-open if needed.

**Closed by Avnerus** 2022-02-28 15:28 UTC
